### ISSUE TITLE
Into_json?

### ISSUE THREAD

**Issue by jwmurray** [ephraimkunz/rs-lcr#191]
Could you add an option to your member_list to output valid json that can be used by other applications?

Thank you very much!  I am not a rust expert, but love your library!

**Comment by ephraimkunz** [comment]
Added this in ffbbce23b08ff195b7ddb5dbc540b9f75e7fd7a4. If you're using the library, the data types now support serialization, so you can serialize into any format supporting serde, such as [serde_json](https://github.com/serde-rs/json). If you're using the command line binary, there's now an output format option to select plaintext or json.
